lvms:
  volumeGroup: vgdatamesh

rbac:
  name: lvms
  namespace: openshift-storage
  roles:
    - createRole: true
      resources:
        - storageclasses
      scope:
        cluster: true
      apiGroups:
        - "storage.k8s.io/v1"
      verbs:
        - "get"
        - "list"
        - "patch"
        - "update"
  roleBindings:
    - name: annotate-sc
    createBinding: true
    scope:
      cluster: true
      namespace: ""
    subjects:
      kind: ServiceAccount
      name: sc-annotater
      namespace: openshift-storage
      apiGroup: ""
    roleRef:
      kind: ClusterRole
      name: sc-mod
